# Generated by Django 5.1.9 on 2025-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitner', '0002_remove_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
